helios-grid-volt-track-module/main/default/objects/Asset/fields/Efficiency_Rating__c.field-meta.xml
<CustomField>
    <fullName>Efficiency_Rating__c</fullName>
    <label>Efficiency Rating</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

helios-grid-sentinel-module/main/default/objects/Work_Order__c/Work_Order__c.object-meta.xml
<CustomObject>
    <label>Work Order</label>
    <nameField>
        <displayFormat>WO-{000}</displayFormat>
        <label>Work Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

helios-grid-sentinel-app/main/default/objects/Work_Order__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account Site</description>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

helios-grid-volt-track-module/main/default/objects/Work_Order__c/fields/Source_Asset__c.field-meta.xml
<CustomField>
    <fullName>Source_Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Source Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

helios-grid-volt-track-module/main/default/objects/Work_Order__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Installation</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>Emergency</fullName>
            </value>
            <value>
                <fullName>Compliance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

helios-grid-volt-track-module/main/default/classes/VOLT_EfficiencyBatch.cls
public with sharing class VOLT_EfficiencyBatch implements Database.Batchable<SObject> {

    // start method: find all Inverters with efficiency below 80%
    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(
            'SELECT Id, Name, AccountId, Efficiency_Rating__c ' +
            'FROM Asset ' +
            'WHERE Efficiency_Rating__c < 80 AND Name LIKE \'%Inverter%\''
            );
    }

    // execute method: process each batch of assets
    public void execute(Database.BatchableContext bc, List<Asset> scope) {
        List<Work_Order__c> maintenanceOrders = new List<Work_Order__c>();

        for (Asset inv: scope){
            maintenanceOrders.add(new Work_Order__c(
                Site__c = inv.AccountId,
                Source_Asset__c = inv.Id,
                Type__c = 'Maintenance',
                Subject__c =  'Automated Efficiency Alert: ' + inv.Name,
                Description__c = 'Asset efficiency dropped to ' + inv.Efficiency_Rating__c + '%. Automated maintenance requested.'
            ));
        }

        if(!maintenanceOrders.isEmpty()){
            insert maintenanceOrders;
        }
    }

    //Finish method: log completion
    public void finish(Database.BatchableContext bc) {
        System.debug('Volt-Track: Efficiency scan complete.');
    }
}