helios-grid-sentinel-module/main/default/objects/Account/fields/Site_Permit_Status__c.field-meta.xml
<CustomField>
    <fullName>Site_Permit_Status__c</fullName>
    <description>Permit status</description>
    <label>Site Permit Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Valid</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

helios-grid-sentinel-module/main/default/objects/Work_Order__c/Work_Order__c.object-meta.xml
<CustomObject>
    <label>Work Order</label>
    <nameField>
        <displayFormat>WO-{000}</displayFormat>
        <label>Work Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

helios-grid-sentinel-app/main/default/objects/Work_Order__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account Site</description>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

helios-grid-sentinel-module/main/default/classes/SEN_WorkOrderHandler.cls
public with sharing class SEN_WorkOrderHandler {
    
    /* @description: Validates associated Site(Account) before Work Order is created */
    public static void verifySiteCompliance(List<Work_Order__c> newWorkOrders) {

        Set<Id> siteIds = new Set<Id>();

        for(Work_Order__c wo: newWorkOrders){
            /* Collect Site Ids(Accounts) from Work Orders */
            if(wo.Site__c != null){
                siteIds.add(wo.Site__c);
            }

            if (siteIds.isEmpty()){
                return;
            }
        }

        Map<Id, Account> siteMap = new Map<Id, Account>([
            SELECT Id, Site_Permit_Status__c
            FROM Account 
            WHERE Id IN :siteIds
        ]);

        for(Work_Order__c wo: newWorkOrders){

            Account parentSite = siteMap.get(wo.Site__c);

            
            if(parentSite != null && parentSite.Site_Permit_Status__c != 'Valid'){

                /* This will check first if parentSite is not null to avoid null pointer exception */
                String currentStatus = parentSite.Site_Permit_Status__c != null ? parentSite.Site_Permit_Status__c : 'Missing';
                wo.addError('Cannot create Work Order. The associated Site does not have a Valid Permit Status. The current Site Permit Status is: ' + currentStatus + '.');
            }

        }

    }
}