helios-grid-sentinel-module/main/default/objects/Account/fields/Site_Permit_Status__c.field-meta.xml
<CustomField>
    <fullName>Site_Permit_Status__c</fullName>
    <description>Permit status</description>
    <label>Site Permit Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Valid</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

helios-grid-sentinel-module/main/default/objects/Work_Order__c/Work_Order__c.object-meta.xml
<CustomObject>
    <label>Work Order</label>
    <nameField>
        <displayFormat>WO-{000}</displayFormat>
        <label>Work Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

helios-grid-sentinel-app/main/default/objects/Work_Order__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account Site</description>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

helios-grid-sentinel-module/main/default/classes/SEN_WorkOrder_Test.cls
@isTest
private class SEN_WorkOrder_Test {

    @isTest
    static void testBlockdWorkOrder() {

        // Create a Site(Account) with invalid permit status
        Account expiredSite = new Account(
            Name = 'Expired Solar Farm',
            Site_Permit_Status__c = 'Expired'
        );
        insert expiredSite;
        
        // Attempt to create a Work Order associated with the invalid Site
        Work_Order__c wo = new Work_Order__c(
            Site__c = expiredSite.Id
        );

        Test.startTest();
        Database.SaveResult result = Database.insert(wo, false);
        Test.stopTest();

        //verify that the Work Order insertion failed
        System.assertEquals(false, result.isSuccess(), 'Work Order insertion should fail due to invalid Site permit status.');
        System.assert(result.getErrors()[0].getMessage().contains('Cannot create Work Order.'), 'Error message should indicate invalid Site permit status.');

    }

    @isTest
    static void testAllowedWorkOrder(){
        // Create a Site(Account) with valid permit status
        Account validSite = new Account(
            Name = 'Valid Solar Farm',
            Site_Permit_Status__c = 'Valid'
        );
        insert validSite;
        
        // Attempt to create a Work Order associated with the valid Site
        Work_Order__c wo = new Work_Order__c(
            Site__c = validSite.Id
        );

        Test.startTest();
        Database.SaveResult result = Database.insert(wo, true);
        Test.stopTest();

        // Verify that the Work Order insertion succeeded
        System.assertEquals(true, result.isSuccess(), 'Work Order insertion should succeed for Site with valid permit status.');
    }




}